app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls', namespace='frontend')),
    path('api/', include('user_auth.urls')),
    path('api/', include('main.urls')),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/frontend/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth import views

app_name = 'frontend'

urlpatterns = [
    path('', TemplateView.as_view(template_name='frontend/index.html'), name='index'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('task/<int:task_id>/', TemplateView.as_view(template_name='frontend/task.html'), name='task'),
    path('login/', TemplateView.as_view(template_name='frontend/login.html'), name='login'),
    path('register/', TemplateView.as_view(template_name='frontend/register.html'), name='register'),
    path('profile/<int:user_id>/', TemplateView.as_view(template_name='frontend/profile.html'), name='profile'),
    path('users/', TemplateView.as_view(template_name='frontend/users.html'), name='users'),
    path('create_task/', TemplateView.as_view(template_name='frontend/create_task.html'), name='create_task'),
    path('user_settings/', TemplateView.as_view(template_name='frontend/user-settings.html'), name='user_settings'),
]

app/frontend/models.py
from django.db import models

# Create your models here.

app/frontend/views.py
from django.shortcuts import render

# Create your views here.

app/frontend/templates/frontend/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}qwe{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'frontend/css/base.css' %}">
</head>
<header>
    <nav class="navbar">
        <div class="container">
            <div class="site-name">
                <h1>People Finder</h1>
            </div>
            <div class="links">
                <a href="{% url "frontend:index" %}">Главная</a>
                <a href="{% url "frontend:create_task" %}">Создать заказ</a>
                <a href="{% url "frontend:users" %}">Пользователи</a>
                {% if user.is_superuser %}
                <a href="{% url "admin:index" %}">Админ панель</a>
                {% endif %}    
            </div>
            
            <div class="actions">
                {% if user.is_authenticated %}
                    <p>Здравствуйте, {{ user.profile.name }}!</p>
                    <div class='dropdown'>
                        <button class='dropdown-button menu-btn'>Меню</button>
                        <div class='dropdown-content'>
                            <a href="{% url "frontend:profile" user_id=user.pk %}">Профиль</a>
                            <a href="{% url "frontend:user_settings" %}">Настройки</a>
                            <a href="{% url "frontend:logout" %}">Выйти</a>
                        </div>
                    </div>
                {% else %}
                    <a href="{% url "frontend:login" %}" class="action-btn">Войти</a>
                    <a href="{% url "frontend:register" %}" class="action-btn">Регистрация</a>
                {% endif %}
            </div>
        </div>
    </nav>
</header>
<body>
{% block content %}{% endblock content %}
</body>
<footer class="footer">
    <div class="container">
        <p>© 2024 People Finder</p>
    </div>
</footer>
</html>

app/frontend/templates/frontend/create-order.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %}Создание заказа{% endblock title %}


{% block content %}
<link rel="stylesheet" href="{% static 'frontend/css/create-order.css' %}">
<div class="content">
    <div class="order-section">
        <h2>Создание заказа</h2>
        <form action="/path_to_your_backend" method="POST">
            <div class="form-group">
                <label for="order-title">Название заказа</label>
                <input type="text" id="order-title" name="title" required>
            </div>
            <div class="form-group">
                <label for="order-description">Описание заказа</label>
                <textarea id="order-description" name="description" required></textarea>
            </div>
            <div class="form-group">
                <label for="order-price">Цена заказа</label>
                <input type="number" id="order-price" name="price" required>
            </div>
            <div class="form-group">
                <label for="order-tags">Теги заказа</label>
                <select id="order-tags" name="tags" multiple>
                            <!-- Тут будут динамически генерироваться теги -->
                </select>

                <div class="form-group">
                    <label for="urgent-order">Срочный заказ</label>
                    <input type="checkbox" id="urgent-order" name="urgent">
                </div>
                

            </div>
            <button type="submit">Создать заказ</button>
        </form>
        
    </div>
</div>

{% endblock content %}

app/frontend/templates/frontend/create_task.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %}Создание заказа{% endblock title %}


{% block content %}
<link rel="stylesheet" href="{% static 'frontend/css/create-order.css' %}">
<div class="content">
    <div class="order-section">
        <h2>Создание заказа</h2>
        <form id="create-order-form" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="order-title">Название заказа</label>
                <input type="text" id="order-title" name="title" required>
            </div>
            <div class="form-group">
                <label for="order-description">Описание заказа</label>
                <textarea id="order-description" name="description" required></textarea>
            </div>
            <div class="form-group">
                <label for="order-price">Цена заказа</label>
                <input type="number" id="order-price" name="price" required>
            </div>
            <div class="form-group">
                <label for="order-tags">Теги заказа</label>
                <select id="order-tags" name="tags" multiple>
                </select>

                <div class="form-group">
                    <label for="urgent-order">Срочный заказ</label>
                    <input type="checkbox" id="urgent-order" name="urgent">
                </div>
                

            </div>
            <button type="submit">Создать заказ</button>
        </form>
        
    </div>
</div>
<script src="{% static 'frontend/js/create-task.js' %}"></script>
{% endblock content %}

app/frontend/templates/frontend/index.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %} Главная {% endblock title %}

{% block content %}

<div class="main">
    <link rel="stylesheet" href="{% static 'frontend/css/index.css' %}">
    <h1 class="titleh1">Заказы</h1>

</div>
<script src="{% static 'frontend/js/index.js' %}"></script>
{% endblock content %}

app/frontend/templates/frontend/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'frontend/css/login-register.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Вход</title>
</head>
<body>
    <form @submit.prevent="signIn()">
        <div class="login-container">
            <h1 class="login-title">Вход в People Finder</h1>

            <div class="login-form">
                <div class="user-name">
                    <label for="username" class="user-login">Логин</label>
                    <input id="login" type="text" placeholder="Введите логин">
                </div>
            
                <div class="user-password">
                    <label for="password">Пароль</label>
                    <input id="password" type="password" placeholder="Введите пароль">
                </div>
            
                <div class="action">
                    <input class="look-btn" value="Войти" type="submit">
                </div>
                <div id="error-message" style="color: red;"></div>
            
                <div class="links">
                    <p>Нет аккаунта? <a href="{% url "frontend:register" %}">Зарегистрироваться</a></p>
                </div>
            </div>
        </div>
    </form>
    


    <script src="{% static 'frontend/js/login.js' %}"></script>
</body>
</html>

app/frontend/templates/frontend/profile.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %}Профиль{% endblock title %}


{% block content %}
<link rel="stylesheet" href="{% static 'frontend/css/profile/profile-data.css'%}">
<link rel="stylesheet" href="{% static 'frontend/css/profile/profile-order.css'%}">

<div class="content">
    <div class="profile-section">
        <div class="profile-info">
            <div class="avatar">
                <img src="" alt="Аватар">
            </div>
            <h2 class="user-name"></h2>
            <ul class="user-details">
                <li><strong>Возраст:</strong> <span></span></li>
                <li><strong>Стаж работы:</strong> <span></span></li>
                <li><strong>Номер телефона: </strong> <span></span></li>
                <li><strong>Почта:</strong> <span></span></li>
                <li><strong>Навыки:</strong> <span></span></li>
            </ul>        
        </div>
    </div>
    <div class="orders-section">
        <h2 class="orders-heading">Взятые заказы</h2>

        <div class="order">
            <h3 class="order-title">Заказ по CSS</h3>
            <div class="action">
                <a href="#" class="look-btn">Посмотреть заказ</a>
            </div>
        </div>
        

        <div class="order">
            <h3 class="order-title">Заказ по CSS</h3>
            <div class="action">
                <a href="#" class="look-btn">Посмотреть заказ</a>
            </div>
        </div>

        <h2 class="orders-heading">Созданные заказы</h2>


        <div class="order">
            <h3 class="order-title">Заказ по CSS</h3>
            <div class="action">
                <a href="#" class="look-btn">Посмотреть заказ</a>
            </div>
        </div>

        <div class="order">
            <h3 class="order-title">Заказ по CSS</h3>
            <div class="action">
                <a href="#" class="look-btn">Посмотреть заказ</a>
            </div>
        </div>
    </div>

</div>

<script src="{% static 'frontend/js/profile.js'%}"></script>



{% endblock content %}

app/frontend/templates/frontend/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'frontend/css/login-register.css' %}">

    <title>Регистрация</title>
</head>
<body>
    <form @submit.prevent="signUp()">
        <div class="login-container">
            <h1 class="login-title">Регистрация в People Finder</h1>

            <div class="login-form">

                <div class="user-name">
                    <label for="name" class="user-login">Имя</label>
                    <input id="name" type="text" placeholder="Введите логин">
                </div>

                <div class="user-name">
                    <label for="login" class="user-login">Логин</label>
                    <input id="login" type="text" placeholder="Введите логин">
                </div>
            
                <div class="user-password">
                    <label for="password1">Пароль</label>
                    <input id="password1" type="password" placeholder="Введите пароль">

                    <label for="password2">Повтор пароля</label>
                    <input id="password2" type="password" placeholder="Введите пароль">

                </div>
            
                <div class="action">
                    <input class="look-btn" value="Регистрация" type="submit">
                </div>
                <div id="error-message" style="color: red;"></div>
            
                <div class="links">
                    <p>Есть аккаунт? <a href="{% url "frontend:login" %}">Войти</a></p>
                </div>
            </div>
        </div> 
    </form> 
</body>
</html>

<script src="{% static 'frontend/js/register.js'%}"></script>

app/frontend/templates/frontend/task.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %}Заказ: Задание по css{% endblock title %}

{% block content %}
<div class="main">
    <link rel="stylesheet" href="{% static 'frontend/css/task.css' %}">
    <h1 class="titleh1"></h1>
    
    <div class="card">
        <div class="header">
            <h2 class="title"></h2>
            <h2 class="user-taken-task"></h2>
            <h2 class="user"></h2>
        </div>
        <p class="description"></p>
        
        <div class="wrap-tag">
            <div class="tags">
                <h3>Теги</h3>
                <div class="tag-container">
                </div>
            </div>
        </div>

        <div class="card-footer">
            <div class="card-price">
                <h2 class="price"></h2>
            </div>
            
            <div class="action">
                <form action="" method="post" id="take-task">
                    {% csrf_token %}
                    <button type="submit" class="look-btn">Взять заказ</button>
                </form>
            </div>
            
        </div>
    </div>
</div>
<script src="{% static 'frontend/js/task.js' %}"></script>
{% endblock content %}

app/frontend/templates/frontend/user-settings.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %}Настройки пользователя{% endblock title %}

{% block content %}
<link rel="stylesheet" href="{% static 'frontend/css/user-settings.css' %}">

<div class="settings">
    <h2>Настройки пользователя</h2>
    <form class="settings-form" id="settings-form" action="" >
        {% csrf_token %}
        <div class="form-group">
            <label for="avatar">Аватар</label>
            <img id="avatar-img" src="">
            <input type="file" id="avatar" name="avatar">
        </div>
        
        <div class="form-group">
            <label for="age">Возраст</label>
            <input type="number" id="age" name="age">
        </div>

        <div class="form-group">
            <label for="experience">Стаж работы</label>
            <input type="number" id="experience" name="experience">
        </div>

        <div class="form-group">
            <label for="phone-number">Номер телефона:</label>
            <input type="number" id="phone-number" name="phone-number">
        </div>

        <div class="form-group">
            <label for="Email">Почта</label>
            <input type="textarea" id="Email" name="Email">
        </div>

        <div class="form-group">
            <label for="skills">Навыки</label>
            <select id="skills" name="skills" multiple></select>
        </div>
        

        <button class="submit-btn" type="submit">Обновить настройки</button>
    </form>
</div>

<script src="{% static 'frontend/js/user-settings.js'%}"></script>
{% endblock content %}

app/frontend/templates/frontend/users.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %}Пользователи{% endblock title %}


{% block content %}
<link rel="stylesheet" href="{% static 'frontend/css/users.css' %}">

<div class="content" id="content">

</div>


<script>
    const DEFAULT_AVATAR_URL = "{% static 'frontend/img/not_found.jpg' %}";
</script>
<script src="{% static 'frontend/js/users.js' %}"></script>

  
{% endblock content %}